### PR TITLE
 datatableCustomDataType html view-source typo

### PR DESCRIPTION
**Pull request by jdpond**
Fix datataleCustomDataType to datatableCustomDataType

### What does this PR do?
Corrects html link to github typo 
### What issues does this PR fix or reference?
#618

## The PR fulfills these requirements:

[ N/A] Tests for the proposed changes have been added/updated.
[ N/A] Code linting and formatting was performed.

### Functionality Before
image

image

### Functionality After

image

### CODE REVIEW

**Comment by jdpond** [comment]
salesforce-cla signed, generating error when clicking on details

**Comment by satyasekharcvb** [comment]
Hi @jdpond, Can you please sign the https://github.com/apps/salesforce-cla

**Comment by jdpond** [comment]
image

**Comment by jdpond** [comment]
image

**Comment by jdpond** [comment]
@satyasekharcvb
The CLA has been signed.

 I think to move this through, you'll have to remove the cla:missing and add the cla:signed label manually.

As far as the other two (format-lint-lwc-tests and scratch-org-test)
1. format-lint-lwc-tests - didn't change anything that should change the lint
2. scratch-org-test - got the "Functionality After" from a scratch site where I tested the updated.

**Pull request merged**
