### PR TITLE
Bump versions as in Bump PRs

### PR DESCRIPTION
**Pull request by satyasekharcvb**
### What does this PR do?
Update npm dependencies - Bumped versions from PRs - #489, #495, #499, and #500

### What issues does this PR fix or reference?
The dependabot issues.

## The PR fulfills these requirements:

[X ] Tests for the proposed changes have been added/updated.
[ X] Code linting and formatting was performed.

### CODE REVIEW

**Comment by adityanaag3** [comment]
`prettier-plugin-apex` also needs to be updated - https://github.com/trailheadapps/lwc-recipes/pull/497

**Comment by satyasekharcvb** [comment]
> @satyasekharcvb `prettier-plugin-apex` also needs to be updated - #497

This update mandates usage of Java Runtime Engine >= 11. It will not work with Java 8. Shall we do it?

**Comment by pozil** [comment]
That's fine as VS Code requires Java >= 11

**Comment by satyasekharcvb** [comment]
> That's fine as VS Code with our extensions requires Java >= 11

Thank you so much. I will do the commit.

**Comment by pozil** [comment]
>  it reads the java version from the JAVA_HOME env variable from the system.

Yes, it has been like that for quite some time looking at the project history (it's not introduced by this release). Anyway, it's a pretty standard thing for a Java program and we need this plugin so go please go ahead and update it.

**Review by pozil — APPROVED** [review]

**Pull request merged**
