### PR TITLE
Feature/apex security

### PR DESCRIPTION
**Pull request by Szandor72**
Added `WITH SECURITY_ENFORCED` to Account and Contact SOQL Queries

### CODE REVIEW

**Comment by pchittum** [comment]
Hi @Szandor72, thanks for submitting this. I'll review this early next week and get back to you.

**Comment by capeterson** [comment]
@Szandor72 it's probably cleaner to merge this once we have `WITH SECURITY_ENFORCED` as GA. I'll know for sure if that's happening in Spring '20 or not in the next couple weeks.

Mind hanging on until I know for sure one way or the other?

**Comment by Szandor72** [comment]
Yes, no worries. I'm happy my intentions were clear. Sorry for confusing
public beta with GA

**Comment by capeterson** [comment]
@Szandor72 WITH SECURITY_ENFORCED went GA in spring as hoped. Since it's live in pre-release I'm okay with this merging now (although I'm not a repo owner to specifically *approve* it).

@pchittum whenever you're ready (and the CI check passes)

**Comment by pchittum** [comment]
@Szandor72 Thanks for doing this! I've merged these changes with pr #216. 

I'll be closing this, but thanks for contributing to this project!

**Pull request closed without merging**
