### PR TITLE
Adding SLDS modal

### PR DESCRIPTION
**Pull request by muenzpraeger**

### CODE REVIEW

**Comment by muenzpraeger** [comment]
@ccoenraets @kevinv11n Because many people miss a modal implementation in base lightning components I added this recipe. LMK what y'all think (before I add Jest stuff).

**Comment by muenzpraeger** [comment]
Fixes #57

**Comment by mrigdon** [comment]
Hi @muenzpraeger,

I'm trying to find an accessible modal implementation for LWC off core & I came across this PR. 

I tested out the MiscModal in a scratch org & found that it is not accessible (focus is not trapped within the modal). Are there plans to make it accessible?

Thanks.

**Comment by muenzpraeger** [comment]
Not yet, @mrigdon. And it's a good point.

I'll put [this implementation](https://www.lightningdesignsystem.com/components/modals/#Accessibility) on the list of things to change with the next revision.

**Pull request merged**
