### PR TITLE
Adding a mock to GenerateURL that returns a Promise.

### PR DESCRIPTION
**Pull request by BatemanVO**
Our team had a dev implement the `NavigationMixin.GenerateUrl` method in a `connectedCallback` similar to [what's detailed in the documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning-navigation/documentation). Unfortunately, when running the test, as soon as the component was appended, an error was received of `cannot read property then of undefined` because the [default implementation is just a stub](https://github.com/salesforce/sfdx-lwc-jest/blob/master/src/lightning-stubs/navigation/navigation.js) that doesn't return a Promise.

Since `NavigationMixin.Navigate` has some extra logic built into the mock to be used in tests, we added something very similar for `GenerateUrl` and thought other developers would also find it useful.

We use `https://www.example.com` as the generated URL since it is a reserved domain that's safe to reference in tests, but provides the structure of a "real" URL. We could just as easily have it be an empty String or some dummy value like "Some URL", though, if that would be preferred. We considered adding in some logic to make the URL configurable in case the implementation cares about what's returned, but ultimately decided that would be enough of an edge case that a developer could add that kind of functionality themselves as needed and what we had was generic enough for most purposes.

### CODE REVIEW

**Comment by BatemanVO** [comment]
Not quite understanding what we should do to resolve the Authenticate Dev Hub check failing, could use some assistance.

**Comment by kevinv11n** [comment]
@trevor-bliss  fyi

**Comment by trevor-bliss** [comment]
@pozil @muenzpraeger Do you know what's up with the failing CI jobs? Are those expected to pass when run from a fork?

**Comment by pozil** [comment]
@trevor-bliss these actions can't pass from a fork because GitHub hides secrets (Dev Hub url in that case) for security reasons.
LWC tests are passing on that PR so we can merge it.

**Comment by pozil** [comment]
I do need to check why the two `packaging` workflows are triggered.

**Comment by muenzpraeger** [comment]
Looks like @trevor-bliss added it to the default mocks, so we can skip the PR.

**Comment by trevor-bliss** [comment]
I'm updating the default stub but this project overrides the default so it won't get those changes. I still think it makes sense for this projects custom stub to return the Promise in GenerateUrl.

**Comment by pchittum** [comment]
Thanks @BatemanVO for your PR.

**Pull request merged**
